modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPLv3"

[[mods]]
modId="ante"
version="1.1"
displayName="Anvil Never Too Expensive"
credits="Huge credit to my constant anger towards the 'Too Expensive' message in the anvil GUI!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/anvil-never-too-expensive"
authors="tinytransfem"
logoFile="logo.png"
description='''Removes the level cap in the anvil GUI.'''

[[dependencies.ante]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,]"
    ordering="NONE"
    side="BOTH"




